### ISSUE TITLE
using Yosemite 10.10 SDK breaks GTK 3.24.10 build

### ISSUE THREAD

**Issue by dehesselle** [dehesselle/mibap#4]
```
/Users/Shared/work/0.27a/opt/src/checkout/gtk+-3.24.10/gdk/quartz/gdkwindow-quartz.c:2195:37: note: expanded from macro 'GDK_QUARTZ_DISALLOWS_TILING'
#define GDK_QUARTZ_DISALLOWS_TILING NSWindowCollectionBehaviorFullScreenDisallowsTiling
                                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:97:5: note: 'NSWindowCollectionBehaviorFullScreenAuxiliary' declared here
    NSWindowCollectionBehaviorFullScreenAuxiliary NS_ENUM_AVAILABLE_MAC(10_7) = 1 << 8      // windows with this collection behavior can be shown with the fullscreen window.
    ^
/Users/Shared/work/0.27a/opt/src/checkout/gtk+-3.24.10/gdk/quartz/gdkwindow-quartz.c:2211:24: error: use of undeclared identifier 'NSWindowCollectionBehaviorFullScreenAllowsTiling'; did you mean 'NSWindowCollectionBehaviorFullScreenAuxiliary'?
                       GDK_QUARTZ_ALLOWS_TILING);
                       ^~~~~~~~~~~~~~~~~~~~~~~~
                       NSWindowCollectionBehaviorFullScreenAuxiliary
/Users/Shared/work/0.27a/opt/src/checkout/gtk+-3.24.10/gdk/quartz/gdkwindow-quartz.c:2194:34: note: expanded from macro 'GDK_QUARTZ_ALLOWS_TILING'
#define GDK_QUARTZ_ALLOWS_TILING NSWindowCollectionBehaviorFullScreenAllowsTiling
                                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:97:5: note: 'NSWindowCollectionBehaviorFullScreenAuxiliary' declared here
    NSWindowCollectionBehaviorFullScreenAuxiliary NS_ENUM_AVAILABLE_MAC(10_7) = 1 << 8      // windows with this collection behavior can be shown with the fullscreen window.
    ^
/Users/Shared/work/0.27a/opt/src/checkout/gtk+-3.24.10/gdk/quartz/gdkwindow-quartz.c:2216:25: error: use of undeclared identifier 'NSWindowCollectionBehaviorFullScreenAllowsTiling'; did you mean 'NSWindowCollectionBehaviorFullScreenAuxiliary'?
                        GDK_QUARTZ_ALLOWS_TILING);
                        ^~~~~~~~~~~~~~~~~~~~~~~~
                        NSWindowCollectionBehaviorFullScreenAuxiliary
```

This happens when changing `MACOSX_DEPLOYMENT_TARGET` to `10.10` in `020-vars.sh`. Reverting back to Mavericks 10.9 SDK for now.

**Comment by dehesselle** [comment]
After applying upstream from upstream gtk-osx, everything compiles fine with SDK 10.10.
Fixed with release 0.29
